@media_vault_app.API_HostAddress = https://localhost:7121
@username = testuser
@email = testuser@example.com
@password = Test123!
@updatedUsername = testuser-updated
@updatedEmail = testuser-updated@example.com

### Register
POST {{media_vault_app.API_HostAddress}}/Auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "confirmEmail": "{{email}}",
  "password": "{{password}}",
  "confirmPassword": "{{password}}"
}

###

### Login
POST {{media_vault_app.API_HostAddress}}/Auth/login
Content-Type: application/json
Accept: application/json

{
  "usernameOrEmail": "{{username}}",
  "password": "{{password}}"
}

###

### Get current user
GET {{media_vault_app.API_HostAddress}}/Auth/me
Accept: application/json

###

### Update current user
PUT {{media_vault_app.API_HostAddress}}/Auth
Content-Type: application/json
Accept: application/json

{
  "userName": "{{updatedUsername}}",
  "email": "{{updatedEmail}}"
}

###

### Logout
POST {{media_vault_app.API_HostAddress}}/Auth/logout
Accept: application/json

###

### TMDB - Search Movies
POST {{media_vault_app.API_HostAddress}}/TmdbApi/movie/search?page=1&pageSize=10
Content-Type: application/json
Accept: application/json

{
  "query": "Inception"
}

###

### TMDB - Get Movie by ID
GET {{media_vault_app.API_HostAddress}}/TmdbApi/movie/550
Accept: application/json

###

### TMDB - Search TV Series
POST {{media_vault_app.API_HostAddress}}/TmdbApi/tv/search?page=1&pageSize=10
Content-Type: application/json
Accept: application/json

{
  "query": "Breaking Bad"
}

###

### TMDB - Get TV Series by ID
GET {{media_vault_app.API_HostAddress}}/TmdbApi/tv/1396
Accept: application/json

###
