<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>media_vault_app.API</RootNamespace>
    <UserSecretsId>f4bdc0ef-0503-4d35-9a1c-19363d91e191</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Megaraz.ResultPattern" Version="0.2.2" />
    <PackageReference Include="Megaraz.ResultPattern.AspNetCore" Version="0.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\media-vault-app.Application\media-vault-app.Application.csproj" />
    <ProjectReference Include="..\media-vault-app.Domain\media-vault-app.Domain.csproj" />
    <ProjectReference Include="..\media-vault-app.Infrastructure\media-vault-app.Infrastructure.csproj" />
  </ItemGroup>

</Project>
