// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using media_vault_app.Infrastructure;

#nullable disable

namespace media_vault_app.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317081010_Change")]
    partial class Change
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("media_vault_app.Domain.Entities.MediaEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdExternal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MediaEntries", t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0.5 AND Rating <= 10 AND Rating * 2 = FLOOR(Rating * 2)");
                        });

                    b.HasDiscriminator<string>("Discriminator").HasValue("MediaEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.MovieEntry", b =>
                {
                    b.HasBaseType("media_vault_app.Domain.Entities.MediaEntry");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0.5 AND Rating <= 10 AND Rating * 2 = FLOOR(Rating * 2)");
                        });

                    b.HasDiscriminator().HasValue("MovieEntry");
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.MediaEntry", b =>
                {
                    b.HasOne("media_vault_app.Domain.Entities.User", null)
                        .WithMany("MediaEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.User", b =>
                {
                    b.Navigation("MediaEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
