// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using media_vault_app.Infrastructure;

#nullable disable

namespace media_vault_app.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427064915_AddMediaEntryHierarchy")]
    partial class AddMediaEntryHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("media_vault_app.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.MediaEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Genres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdExternal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MediaEntries", t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0 AND Rating <= 5 AND Rating * 2 = FLOOR(Rating * 2)");
                        });

                    b.HasDiscriminator<int>("MediaType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Episodes")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TvSeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WatchedEpisodes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TvSeriesId");

                    b.ToTable("Seasons", t =>
                        {
                            t.HasCheckConstraint("CK_Season_Rating", "Rating >= 0 AND Rating <= 5 AND Rating * 2 = FLOOR(Rating * 2)");
                        });
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.AuthoredEntry", b =>
                {
                    b.HasBaseType("media_vault_app.Domain.Entities.MediaEntry");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AuthorId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0 AND Rating <= 5 AND Rating * 2 = FLOOR(Rating * 2)");
                        });
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.GameEntry", b =>
                {
                    b.HasBaseType("media_vault_app.Domain.Entities.MediaEntry");

                    b.Property<string>("DevStudioName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0 AND Rating <= 5 AND Rating * 2 = FLOOR(Rating * 2)");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.MovieEntry", b =>
                {
                    b.HasBaseType("media_vault_app.Domain.Entities.MediaEntry");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0 AND Rating <= 5 AND Rating * 2 = FLOOR(Rating * 2)");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.TvSeriesEntry", b =>
                {
                    b.HasBaseType("media_vault_app.Domain.Entities.MediaEntry");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("int");

                    b.Property<int>("TotalWatchedEpisodes")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0 AND Rating <= 5 AND Rating * 2 = FLOOR(Rating * 2)");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.BookEntry", b =>
                {
                    b.HasBaseType("media_vault_app.Domain.Entities.AuthoredEntry");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0 AND Rating <= 5 AND Rating * 2 = FLOOR(Rating * 2)");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.MangaEntry", b =>
                {
                    b.HasBaseType("media_vault_app.Domain.Entities.AuthoredEntry");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_MediaEntry_Rating", "Rating >= 0 AND Rating <= 5 AND Rating * 2 = FLOOR(Rating * 2)");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.MediaEntry", b =>
                {
                    b.HasOne("media_vault_app.Domain.Entities.User", null)
                        .WithMany("MediaEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.Season", b =>
                {
                    b.HasOne("media_vault_app.Domain.Entities.TvSeriesEntry", null)
                        .WithMany("Seasons")
                        .HasForeignKey("TvSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.AuthoredEntry", b =>
                {
                    b.HasOne("media_vault_app.Domain.Entities.Author", "Author")
                        .WithMany("AuthoredEntries")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.Author", b =>
                {
                    b.Navigation("AuthoredEntries");
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.User", b =>
                {
                    b.Navigation("MediaEntries");
                });

            modelBuilder.Entity("media_vault_app.Domain.Entities.TvSeriesEntry", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
